pages:
  image: node:latest
  stage: deploy
  environment: production
  cache:
    key: build-cache
    paths:
      - node_modules/
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - dist
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
