name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    outputs:
      release-exists: ${{ steps.check-files.outputs.files_exists }}

    steps:
      - uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Biome CI
        run: pnpm biome ci .

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: semantic
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/changelog@6.0
            @semantic-release/exec@6.0
            @semantic-release/git@10.0

      - name: Check file existence
        id: check-files
        uses: andstor/file-existence-action@v3
        with:
          files: "dist-release"

      - name: Upload artifact
        if: steps.check-files.outputs.files_exists == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist-release

  deploy:
    needs: release
    if: ${{ needs.release.outputs.release-exists == 'true' }}
    name: "Deploy"
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
